#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=ghimindama11R

spring.security.user.name=alex
spring.security.user.password=pula
